CREATE TABLE IF NOT EXISTS Action_Type (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL
);

INSERT OR IGNORE INTO Action_Type  VALUES (0, 'Approve');
INSERT OR IGNORE INTO Action_Type VALUES  (1, 'Delete');
INSERT OR IGNORE INTO Action_Type VALUES  (2, 'Ban User');
INSERT OR IGNORE INTO Action_Type VALUES  (3, 'Reply');

CREATE TABLE IF NOT EXISTS Actions (
  id  INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  type INTEGER NOT NULL,
  message TEXT,
  FOREIGN KEY (type) REFERENCES Action_Type
);

CREATE TABLE IF NOT EXISTS Triggers (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  type INTEGER NOT NULL,
  regex TEXT,
  sample_set INTEGER,
  bad_sample_set INTEGER,
  FOREIGN KEY (sample_set) REFERENCES CommentSampleSets,
  FOREIGN KEY (bad_sample_set) REFERENCES CommentSampleSets
);

CREATE TABLE IF NOT EXISTS Rules (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  trigger INTEGER NOT NULL,
  action INTEGER NOT NULL,
  subreddit TEXT,
  FOREIGN KEY (action) REFERENCES Actions,
  FOREIGN KEY (trigger) REFERENCES Triggers,
  UNIQUE (trigger, action, subreddit)
);

CREATE TABLE IF NOT EXISTS Settings (
  key TEXT PRIMARY KEY UNIQUE NOT NULL,
  value TEXT NOT NULL

);

CREATE TABLE IF NOT EXISTS CommentSampleSets (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  name TEXT UNIQUE NOT NULL,
  done BOOLEAN
);

CREATE TABLE IF NOT EXISTS Comments (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  reddit_id TEXT NOT NULL,
  sample_set INTEGER NOT NULL,
  user TEXT NOT NULL,
  num_words INTEGER NOT NULL,
  UNIQUE (reddit_id, sample_set),
  FOREIGN KEY (sample_set) REFERENCES CommentSampleSets
);

CREATE TABLE IF NOT EXISTS Words (
  word TEXT PRIMARY KEY UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Subreddits (
  subreddit TEXT PRIMARY KEY UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS WordCounts (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  comment INTEGER  NOT NULL,
  word TEXT NOT NULL,
  count INTEGER NOT NULL,
  FOREIGN KEY (comment) REFERENCES Comments,
  FOREIGN KEY (word) REFERENCES Words,
  UNIQUE (comment, word)
);

CREATE TABLE IF NOT EXISTS Stats (
  id INTEGER PRIMARY KEY ASC AUTOINCREMENT UNIQUE NOT NULL,
  word TEXT NOT NULL,
  sample_set INTEGER NOT NULL,
  count INTEGER NOT NULL,
  mean_count REAL NOT NULL,
  median_count REAL NOT NULL,
  std_dev REAL NOT NULL,
  mad_count REAL NOT NULL,
  FOREIGN KEY (word) REFERENCES Words,
  FOREIGN KEY (sample_set) REFERENCES CommentSampleSets,
  UNIQUE (word, sample_set)
);



